"""Tables [User , Project]

Revision ID: 9979441ba221
Revises: 
Create Date: 2020-07-13 16:26:59.246679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9979441ba221'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=124), nullable=True),
    sa.Column('firstname', sa.String(length=124), nullable=True),
    sa.Column('lastname', sa.String(length=124), nullable=True),
    sa.Column('email', sa.String(length=124), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('avatar', sa.String(length=124), nullable=True),
    sa.Column('about_me', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=124), nullable=True),
    sa.Column('company', sa.String(length=124), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=124), nullable=True),
    sa.Column('body', sa.String(length=500), nullable=True),
    sa.Column('avatar', sa.String(length=124), nullable=True),
    sa.Column('tech', sa.String(length=124), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
